# -*- coding: utf-8 -*-
"""Countdown_telegram bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Ujyd1YVI46U8oNHYX-GPdDuOALzT2zv
"""

! pip install pyTelegramBotAPI

! pip install schedule

import telebot
from datetime import datetime, timedelta
import time
from telebot.apihelper import ApiTelegramException
import schedule

# Замените 'YOUR_BOT_TOKEN' на токен вашего бота
bot = telebot.TeleBot('7294943213:AAGJGOXFPRzloQACxAjCTfLf4NBa3nmPEkM')

# ID целевого чата (замените на реальный ID)
TARGET_CHAT_ID = -250785345  # Васеленная

# Глобальная переменная для хранения даты окончания отсчета
end_date = None

def set_countdown(days):
    global end_date
    end_date = datetime.now() + timedelta(days=days)

def send_daily_update():
    global end_date
    if end_date:
        remaining_time = end_date - datetime.now()
        if remaining_time.total_seconds() > 0:
            days = remaining_time.days
            bot.send_message(TARGET_CHAT_ID, f"Осталось дней: {days}")
        else:
            bot.send_message(TARGET_CHAT_ID, "Время вышло!")
            end_date = None

# Функция для запуска бота
def run_bot():
    schedule.every().day.at("09:00").do(send_daily_update)  # Отправка сообщения каждый день в 9:00

    while True:
        schedule.run_pending()
        time.sleep(1)

if __name__ == "__main__":
    # Установите начальную дату окончания отсчета (например, на 60 дней)
    set_countdown(60)

    try:
        run_bot()
    except Exception as e:
        print(f"Произошла ошибка: {e}")